name: PR Repository Checks and Tests
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  merge_group:
    types: [checks_requested]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Check linting and formatting
      - id: check_lint_format
        name: Lint and Format
        run: |
          echo 'checked'
